version: "2" # Versión del esquema YAML de docker-compose que estamos usando

services:
    weblogic:
        container_name:     miwl
        image:              container-registry.oracle.com/middleware/weblogic:12.2.1.4
        environment:
            CONFIG_JVM_ARGS:             "-Dweblogic.security.TrustKeyStore=DemoTrust"
        #    DOMAIN_NAME:                base_domain
        #    ADMIN_NAME:                 AdminServer
        #    ADMIN_LISTEN_PORT:          "7001"
        #    PRODUCTION_MODE:            prod
        #    ADMINISTRATION_PORT_ENABLED: "false"
        #    ADMINISTRATION_PORT:        "9002"
        ports:
                          - 7001:7001
                          - 7011:7011
                          - 9002:9002
        volumes:
                          - ./domain.properties:/u01/oracle/properties/domain.properties
                          - /home/ubuntu/environment/curso/scripts:/scripts
                          - /home/ubuntu/environment/datos/weblogic/dominios:/u01/oracle/user_projects/domains/
        networks:
                          - red-propia
        restart:            always
        
    weblogic2:
        container_name:     miwl2
        image:              container-registry.oracle.com/middleware/weblogic:12.2.1.4
        environment:
            CONFIG_JVM_ARGS:             "-Dweblogic.security.TrustKeyStore=DemoTrust"
        ports:
                          - 7031:7001
                          - 7041:7001
                          - 9042:9002
                          - 9032:9002
        volumes:
                          - ./domain.properties:/u01/oracle/properties/domain.properties
                          - /home/ubuntu/environment/curso/scripts:/scripts
                          - /home/ubuntu/environment/datos/weblogic/dominios2:/u01/oracle/user_projects/domains/
        networks:
                          - red-propia
        command:            /u01/oracle/user_projects/domains/base_domain/bin/startNodeManager.sh
        restart:            always
networks:
    red-propia: # Con este nombre me refiero a la red dentro de este fichero
        name: mi-red  # Este nombre es con el que gestiono a esta red, dentro de docker
# docker login container-registry.oracle.com
# docker compose up -d:   CREA Y ARRANCA LOS CONTENEDORES
# docker compose down:  PARA Y BORRA LOS CONTENEDORES
# docker compose start: ARRANCA LOS CONTENEDORES, si ya existen
# docker compose stop:  DETIENE LOS CONTENEDORES, si están corriendo y creados
# docker compose restart
