version: "2" # Versión del esquema YAML de docker-compose que estamos usando

services:
    mysql:
        container_name:     mimysql
        image:              mysql:8.0
        environment:
                            MYSQL_ROOT_PASSWORD:    password
                            MYSQL_DATABASE:         basedatos
                            MYSQL_USER:             usuario
                            MYSQL_PASSWORD:         password
        volumes:
                            # Los datos, según está configurada la imagen de mysql creada por Oracle
                            # se guardan en /var/lib/mysql (me lo cuenta la documentación de la imagen)
                          - /home/ubuntu/environment/datos/mysql:/var/lib/mysql
        networks:
                          - red-propia

networks:
    red-propia:
        external:   true    # Esta red ya existe, se creó en otro fichero docker compose.
        name:       mi-red 